title: Wiki

baseurl: ''
url: https://example.com

#disqus: https://your-disqus-url.disqus.com

github:
  org: adborden
  repository: jekyll-theme-wiki

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      type: wiki
    values:
      layout: wiki-page
      comments: true
